config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'restaurants/index'
  get 'renstaurants/index'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :microposts, only: %i[create destroy edit update index] do
    resources :comments, only: %i[create index]
  end
  resources :comments, only: %i[edit update destroy]
  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :restaurants, only: %i[index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 100 }

  belongs_to :user
  belongs_to :micropost
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :logged_in_user, only: %i[create edit destroy]
  before_action :correct_user,   only: %i[destroy edit]
  def create
    @comment = current_user.comments.build(comment_params)
    @micropost = Micropost.find(params[:micropost_id])
    @comment.micropost_id = @micropost.id

    @comments = Comment.where(micropost_id: params[:micropost_id])

    @comment.save
    respond_to :js
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = 'コメントの更新が完了しました'
      redirect_to root_path
    else
      respond_to :js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_to root_path
  end

  def index
    @comment = current_user.comments.build
    @comments = Comment.where(micropost_id: params[:micropost_id])
    @micropost = Micropost.find(params[:micropost_id])
    respond_to :js
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_url if @comment.nil?
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'ログインしてください'
    redirect_to login_url
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.slim
- comments.each do |comment| 
  .comment-form
    .prof
      = image_tag comment.user.picture.url,:size =>'50x50', :class => "img-circle"
      = link_to user_path(comment.user) do
        =comment.user.name
    .menu1
      -if logged_in? && current_user?(comment.user)
          .btn-group role="group"
            = link_to edit_comment_path(comment),class: "btn btn-default comment_edit_#{comment.id}",remote:true do
              span.glyphicon.glyphicon-pencil aria-hidden="true"
            = link_to comment, method: :delete,class: "btn btn-default comment_delete_#{comment.id}" do
              span.glyphicon.glyphicon-trash aria-hidden="true"
    
            div#editmodal class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"
    .balloon1-left
      p= comment.content

app/views/comments/_form.html.slim
=form_for @comment,url: micropost_comments_path ,remote:true do |f|
  = render 'shared/error_messages', object: f.object
  =f.text_field :content,placeholder:"コメントを入力",class: "comment-content content_#{@micropost.id}"
  = hidden_field_tag :micropost_id,@micropost.id
  .btn-parent
    =f.submit 'コメント', class: "comu btn btn-primary"
  

app/views/comments/create.js.erb
$('.slide_<%= @micropost.id %>').html("<%= j(render 'comments/comment', comments: @comments) %>");
$('.form_<%= @micropost.id %>').html("<%= j(render 'comments/form', comment: @comment) %>");
$('.content_<%=@micropost.id %>').val("");
$('.slide_<%= @micropost.id %>').scrollTop($('.slide_<%= @micropost.id %>').get(0).scrollHeight);

app/views/comments/edit.js.erb
$("#editmodal").html("<%= j(render'shared/edit_form',title:"コメント",object: @comment) %>")
$("#editmodal").modal("show")

app/views/comments/index.js.erb
$('.slide_<%= @micropost.id %>').html("<%= j(render 'comments/comment',comments:@comments,micropost:@micropost) %>");
$('.form_<%= @micropost.id %>').html("<%= j(render 'comments/form') %>");

var val = <%= @micropost.id %>;
$('.comment_form_' + val ).slideDown();
$('.slide_'+ val).scrollTop($('.slide_'+ val).get(0).scrollHeight);
$('.btn-opn_' + val).hide();
$('.btn-cls_' + val).css('display','inline') ; 

app/views/comments/update.js.erb
$(".edit-form").html("<%= j(render'shared/edit_form',title:"コメント",object: @comment) %>")