config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'restaurants/index'
  get 'renstaurants/index'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :microposts, only: %i[create destroy edit update index] do
    resources :comments, only: %i[create index]
  end
  resources :comments, only: %i[edit update destroy]
  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :restaurants, only: %i[index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :introduce, length: { maximum: 100 }
  mount_uploader :picture, PictureUploader
  validate :picture_size

  # いいね
  has_many :likes, dependent: :destroy
  has_many :likeposts, through: :likes, source: :micropost
  # # コメント
  has_many :comments

  # いいね追加
  def good(micropost)
    likeposts << micropost
  end

  # いいね削除
  def notgood(micropost)
    like = likes.find_by(micropost_id: micropost.id)
    like&.destroy
  end

  # いいね登録判定
  def likepost?(micropost)
    likeposts.include?(micropost)
  end

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # 永続ログインの解除
  def forget
    update_attribute(:remember_digest, nil)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # # 必要な投稿を取得
  def feed
    Micropost.where("user_id IN (:following_ids)
    OR user_id     =   :user_id",
                    following_ids: following_ids, user_id: id).includes([:user])
  end

  private

  # アップロード画像のサイズを検証する
  def picture_size
    errors.add(:image, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

# end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :admin_user, only: :destroy
  before_action :correct_user, only: %i[edit update]
  def show
    @user = User.find(params[:id])
    @microposts = Micropost.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = '登録成功'
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '更新完了'
      redirect_to @user
    else
      render :edit
    end
  end

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(created_at: :desc)
               .page(params[:page]).per(10)
  end
  def likes
    @user = User.find(params[:id])
    @microposts = @user.likeposts
    render :show
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'ユーザーは削除されました'
    redirect_to users_url
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render :show_follow
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render :show_follow
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture,
                                 :unique_name, :address1, :address2, :zipcode, :introduce)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(current_user) unless @user == current_user
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_profile.html.slim
.user-pofile
  .user-pic.text-center
    = image_tag user.picture.url, size:'100x100'
  .user-name.text-center
    h1= user.name
  -if user.introduce.present?
    .user-introduce.balloon1-left
      = user.introduce
    
  -if logged_in?
    -if current_user?(@user)
      .edit-btn.text-center
        = link_to 'プロフィール編集', edit_user_path(@user), class:'btn btn-primary'
    -else
      div class="relation-btn_#{user.id} text-center"
        =render 'relationships/relationship', user:@user

app/views/users/_tab.html.slim
ul.nav.nav-tabs.nav-justified
    li class="#{'active' if current_page?(user_path(@user))}"
      =link_to user_path(@user) do 
        =@user.microposts.count
        |投稿
    li class="#{'active' if current_page?(likes_user_path(@user))}"
      =link_to likes_user_path(@user) do 
        =@user.likes.count
        |いいね
    li class="#{'active' if current_page?(following_user_path(@user))}"
      =link_to following_user_path(@user) do
        = @user.following.count
        |フォロー
    li class="#{'active' if current_page?(followers_user_path(@user))}"
      =link_to followers_user_path(@user) do
        = @user.followers.count
        |フォロワー

app/views/users/_user.html.slim
.post
    .prof
      = image_tag user.picture.url,:size =>'50x50', :class => "img-circle"
      = link_to user_path(user) do
        = user.name
    .menu1
      - if logged_in? && !current_user?(user) 
       div class="relation-btn_#{user.id} text-right"
         = render 'relationships/relationship', user: user
    .content
    -if user.introduce.present?
      .balloon1-left
    /     =user.introduce
    / - if logged_in?
    /   - if current_user.admin? && !current_user?(user) 
    /     li= link_to 'delete', user_path(user), method: :delete

app/views/users/edit.html.slim
- provide(:title, 'ユーザー編集')

h1 ユーザー編集
.row
  .col-md-6.col-md-offset-3
    = form_with(model:@user,local: true) do |f|
      = render 'shared/error_messages', object: f.object
      .edit-profile
        = image_tag @user.picture.url, size:'100x100'
      = f.label :picture, "ユーザー画像"
      = f.file_field :picture, class:'btn btn-default'
      = f.label :name, class: 'col-form-label'
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
      = f.label :introduce
      = f.text_area :introduce, class: 'form-control',size:"30x5"     
      = f.submit "更新", class: "btn btn-primary"

app/views/users/index.html.slim
.search
  = search_form_for @q do |f|
    = f.search_field :name_or_introduce_cont,placeholder:"ユーザー名を検索", class: "form-control"
    .btn-parent
      = f.submit "ユーザーを検索", class: "btn btn-primary"

- if @users.any?
  = render @users
    = paginate @users

app/views/users/new.html.slim
- provide(:title, '新規登録')
h1
  | 新規登録
.row
  .col-md-6.col-md-offset-3
    = form_with(model:@user,local:true) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "新規登録", class: "btn btn-primary"

app/views/users/show.html.slim
/ = render 'users/profile', user:@user
/ = render 'users/tab', user:@user
/ - if @user.microposts.any?
/   = render @microposts

app/views/users/show_follow.html.slim
= render 'users/profile', user:@user
= render 'users/tab', user:@user
= render @users