config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'restaurants/index'
  get 'renstaurants/index'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :microposts, only: %i[create destroy edit update index] do
    resources :comments, only: %i[create index]
  end
  resources :comments, only: %i[edit update destroy]
  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :restaurants, only: %i[index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :pictures, length: { maximum: 4,
                                 too_long: 'は%{count}枚以内で入力してください' }
  belongs_to :user
  default_scope -> { order(updated_at: :desc) }

  mount_uploaders :pictures, PictureUploader
  # serialize :pictures, JSON
  validate :picture_size

  has_many :likes, foreign_key: 'micropost_id', dependent: :destroy
  has_many :users, through: :likes

  has_many :comments, dependent: :destroy

  private

  # アップロード画像のサイズを検証する
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if pictures.size > 5.megabytes
  end
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[create edit destroy]
  before_action :correct_user,   only: %i[destroy edit]

  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save
      flash[:success] = '投稿が完了しました'
      redirect_to root_path
    else
      @feed_items = current_user.feed.page(params[:page]).per(10)
      flash.now[:danger] = '投稿に失敗しました'
      render 'static_pages/home'

    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update(micropost_params)
      flash[:success] = '編集が完了しました'
      redirect_to root_path
    else
      respond_to :js
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to request.referer || root_url
  end

  def index
    @q = Micropost.ransack(params[:q])
    @microposts = @q.result.order(created_at: :desc)
                    .page(params[:page]).per(10)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture, :updated_at, pictures: [])
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'ログインしてください'
    redirect_to login_url
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/_edit_form.html.slim
.container.edit-form
  .modal-daialog
    .modal-content
      .modal-header
        .modal-title
        = title + "を編集" 
      .modal-body
        = form_with(model:object,remote: true) do |f|
          = render 'shared/error_messages', object: f.object
          = f.text_area :content, class: 'form-control edit-area'
          .btn-space
            = f.submit "更新", class: "btn btn-primary"
      .modal-footer
        button type="button" class="btn btn-default" data-dismiss="modal"
          |閉じる 

app/views/microposts/_micropost.html.slim
.post
  .prof
    = image_tag micropost.user.picture.url,:size =>'50x50', :class => "img-circle"
    = link_to user_path(micropost.user) do
      = micropost.user.name
  //編集フォーム、削除 
  
  .menu1
    -if logged_in? && current_user?(micropost.user)
        .btn-group role="group"
          = link_to edit_micropost_path(micropost),class: "btn btn-default micropost_edit_#{micropost.id}",remote:true do
            span.glyphicon.glyphicon-pencil aria-hidden="true"
          = link_to micropost, method: :delete,class: "btn btn-default micropost_delete_#{micropost.id}" do
            span.glyphicon.glyphicon-trash aria-hidden="true"
        div#editmodal class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"
  
  .content
    .balloon1-left
      p= micropost.content 
  
    -if micropost.pictures?
      .row
        -micropost.pictures.each do |p|  
          .col-xs-6.col-md-3
            =image_tag p.url, multiple: true,class: "mwidth" 

  
    div class="comment comment_form_#{micropost.id}" id="comment" 
      div class="slide slide_#{micropost.id}" value="#{micropost.id}" style="height:#{comment_height(micropost.comments.count)}px"
      div class="form form_#{micropost.id}"

    //コメントフォームの表示、非表示、いいね
  .menu2
    - if logged_in?
      = link_to micropost_comments_path(micropost.id),id:"opnbtn",class:"btn btn-opn_#{micropost.id}",remote: true  do
        span.glyphicon.glyphicon-comment aria-hidden="true" 
        
      div class="btn btn-cls_#{micropost.id}" value="#{micropost.id}" id="clsbtn"
        span.glyphicon.glyphicon-remove aria-hidden="true"

      div id="likes_buttons_#{micropost.id}" class="like"
        = render 'likes/like', micropost: micropost

      -if micropost.title.present?
        .search1
          = form_with url: restaurants_path,method: :get,local: true do |f|
            = f.hidden_field :name,value:micropost.title, placeholder: "お店名を入力", class: 'form-control'
            = button_tag( class: "btn micropost_search_#{micropost.id}") do
              span.glyphicon.glyphicon-search aria-hidden="true"
            

app/views/microposts/edit.js.erb
$("#editmodal").html("<%= j(render'shared/edit_form',title:"投稿",object: @micropost) %>")
$("#editmodal").modal("show")

app/views/microposts/index.html.slim
.search
   = search_form_for @q do |f|
    = f.search_field :content_cont,placeholder:"投稿を検索", class: "form-control"
    .btn-parent
      = f.submit "投稿を検索", class: "btn btn-primary"

- if @microposts.any?
  = render @microposts
  = paginate @microposts

app/views/microposts/update.js.erb
$(".edit-form").html("<%= j(render'shared/edit_form',title:"投稿",object: @micropost) %>")