config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'restaurants/index'
  get 'renstaurants/index'
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :microposts, only: %i[create destroy edit update index] do
    resources :comments, only: %i[create index]
  end
  resources :comments, only: %i[edit update destroy]
  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :restaurants, only: %i[index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.slim
  - flash.each do |message_type,message|
    = content_tag(:div, message, class: "alert alert-#{message_type}")

app/views/layouts/_footer.html.slim
.container
  footer
    <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
    <img src="https://api.gnavi.co.jp/api/img/credit/api_90_35.gif" width="90" height="35" border="0" alt="グルメ情報検索サイト　ぐるなび">
    </a>

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
    .container
      .navbar-header 
        button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-left[href= root_path ]
          img.logo [src= '/assets/logo07.png']
      .collapse.navbar-collapse#navbar-content
        ul.nav.navbar-nav.navbar-right
          - if logged_in?
            li.nav-item
              
                .dropdown
                  button class="dropdown-toggle"  id="dropdownmenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                    = image_tag current_user.picture.url,:size =>'20x20', :class => "img-circle"
                    = "  " + current_user.name + "さん"
                    span class="caret"
                  ul class="dropdown-menu"
                    li = link_to "マイページ",current_user
                    li = link_to "ログアウト",logout_path, method: :delete
            li.nav-item = link_to "お店検索", restaurants_path
            li.nav-item = link_to "ユーザー一覧",users_path
            li.nav-item = link_to "投稿検索",microposts_path

          - else
            li.nav-item = link_to "新規登録", signup_path 
            li.nav-item = link_to "ログイン", login_path
            li.nav-item = link_to "お店検索", restaurants_path

app/views/layouts/application.html.slim
doctype html
html
  head
    
    title
      |
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]

  body
    = render 'layouts/header'
    .container.main
      = render 'layouts/flash_messages'
      = yield
    / /div#samplemodal class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"
    = render 'layouts/footer'